#!/bin/sh

ssh ubuntu@18.130.249.32 <<EOF
    cd ~/test-angular-jenkins
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v9.4.0
    npm install
    npm run build
    sudo apt update
    sudo apt install nginx
    sudo chmod 777 /var/www/html/*
    sudo cp -r ./build/ /var/www/html/
    sudo systemctl restart nginx
    exit
EOF