#!/bin/sh

ssh ubuntu@18.130.249.32 <<EOF
    cd ~/test-angular-jenkins
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v12.18.3
    sudo apt update
    sudo apt install nginx
    sudo chmod 777 /var/www/html/*
    npm install
    npm install -g @angular/cli
    ng -v 
    npm run build
    sudo cp -r build/ /var/www/html/
    sudo service nginx restart
    sudo service nginx status
    exit
EOF